Create CODE_OF_CONDUCT.md
DiPA-Projekt/hub-server pull request #9
Opened 2020-09-04 04:22 UTC by martinoppitz

2020-09-04 10:52 UTC, navismo requested changes

2020-09-04 10:52 UTC, navismo commented on CODE_OF_CONDUCT.md
> +reported by contacting the project team at oss@dipa.online. All
Bitte Mail-Adresse änden in info@dipa.online

2020-09-14 11:40 UTC, martinoppitz commented on CODE_OF_CONDUCT.md
> +reported by contacting the project team at oss@dipa.online. All
done

2020-09-14 12:01 UTC, navismo approved these changes

2020-09-14 12:02 UTC, navismo commented on CODE_OF_CONDUCT.md
> +reported by contacting the project team at oss@dipa.online. All
Danke!

2020-09-14 12:04 UTC, merged